In [7]:
import numpy as np

arr_list = [1, 2, 3, 4]
arr = np.array(arr_list)
# print(arr)

zeroes = np.zeros((3, 3))
# print(zeroes)

ones = np.ones((2, 5))
print(ones)

arange = np.arange(1, 10, 2)
print(arange)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1 3 5 7 9]
