In [1]:
print('Hello world')

Hello world


In [1]:
isinstance({1: "one", 2: "two"}, dict)


True

In [2]:
# issubclass
class Parent: 
    pass

class Child(Parent):
    pass

issubclass(Child, Parent)


True

In [ ]:
my_list = [1, 9, 7, 19, 10]
my_iter = iter(my_list)

for list in my_iter:
    print(list)



1
9
7
19
10


In [16]:
my_list = [1, 2, 3, 4, 5]
my_slice = slice(1, 3)
my_list[my_slice]


[2, 3]

In [1]:
sentence = "This is a sentence"
print(sentence[5:7])

is


In [ ]:
phrase = "This is a phrase"
print(phrase)

phrase = "1" + phrase[1:]
print(phrase)


This is a phrase
1his is a phrase


In [3]:
print("This is just a text with number {}".format(34))


This is just a text with number 34


In [2]:
a = 10
b = 3

print(a / b)
print(round(a / b))


3.3333333333333335
3


In [9]:
num = input("Insert a number: ")
num = int(num)

if num < 0:
    print('The given number is smaller than 0')
elif num >= 0 and num <= 10:
    print('The given number is within the range 0 and 10')
else:
    print('The given number is greater than 10')


The given number is greater than 10


In [14]:
counter = 0
total = 0

for num in range(6):
    total += num
    counter += 1

average = total / counter
print(average)


2.5


In [18]:
for num in range(0, 10, 2):
    if num == 5 and num == 6 and num == 7:
        continue
    print(num)
else:
    print('The for loop is finished')


0
2
4
6
8
The for loop is finished


In [2]:
a, b = 0, 1

for counter in range(1, 10):
   print(a)
    
   a, b = b, a + b


0
1
1
2
3
5
8
13
21


In [3]:
def show_name(*names):
    for idx in range(len(names)):
        print(names[idx])

show_name("Peter", "Paul", "Ann", "Joe", "John")


Peter
Paul
Ann
Joe
John


In [5]:
def operation(x):
    if x % 2 == 0:
        return True, 1
    else:
        return False, -1
    
result = operation(10)
print(result[0])
print(result[1])



True
1


In [6]:
def number(x):
    if x < 0:
        return 0
    else:
        return 1
    
num = number(10)
print(num)


1


In [8]:
def producer():
    for num in range(0, 10, 1):
        if num % 2 == 0:
            yield num

for num in producer():
    print(num)


0
2
4
6
8


In [ ]:
def recursive_function(text, index):
    if index == 0:
        return text[0]
    return recursive_function(text, index(n - 1))



In [ ]:
# [5, 10]
def square_num():
    numbers = [5, 10]
    square_n = []
    for num in numbers:
        square_n = square(num).append



In [2]:
names = {'Adam', 'Daniel', 'Ana'}
ages = {34, 12, 54}

my_dict = {}

for key, value in zip(names, ages):
    my_dict[key] = value

print(my_dict)


{'Adam': 34, 'Ana': 12, 'Daniel': 54}


In [14]:
# my_number = [3, 5, 10, 20, 2, -8]
# result = sorted(my_number, reverse=True)
# print(result)

def dict_length(x):
    return x[1]

my_dict = {'Pet': 20, 'Juli': 5, 'Claudia': 10, 'Anna Summer': 8}
dict_result = sorted(my_dict.items(), key=dict_length)
print(dict_result)
print(type(dict_result))


[('Juli', 5), ('Anna Summer', 8), ('Claudia', 10), ('Pet', 20)]
<class 'list'>


In [21]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def show_name(self):
        print('The person name is %s and age is %s' % (self.name, self.age))

person = Person('Peter', 30)
person.show_name()


The person name is Peter and age is 30


In [13]:
class Car:
    __color = 'black'

    def __init__(self, brand, year):
        self.brand = brand
        self.year = year

    def get_brand(self):
        return self.brand
    
    def get_year(self):
        return self.year

car = Car('Pegeuot', 2015)
print(car.get_brand())
print(car.get_year())

print(car._Car__color)


Pegeuot
2015
black


In [24]:
class User:
    anonymous = "Unknown"

    def __init__(self, name, age):
        self.name = name
        self.age = age

    def show_name(self):
        print('The name is %s and the age is %s' % (self.name, self.age))

class FBUser(User):
    def __init__(self, name, age):
        super().__init__(name, age)

userFB = FBUser('Peter', 25)
userFB.show_name()


The name is Peter and the age is 25


In [13]:
class Person:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def __str__(self):
        return 'The person name is %s and age is %s' % (self.name, self.age)
    
    def __lt__(self, other):
        return self.age < other.age

person = Person('Selome', 31)
print(person)

person2 = Person('Sally', 32)
person3 = Person('Sal', 32)
print(person < person3)


The person name is Selome and age is 31
True


In [26]:
import numpy as np 

py_list = [1, 2, 3, 4, 5]

np_array = np.array(py_list)
print(np_array)
print(type(np_array))

arr = np.array([6, 7, 8, 9])
print(arr)

arr[1] = True
print(arr)

arr_insert = np.insert(arr, 0, 5)
print(arr_insert)



[1 2 3 4 5]
<class 'numpy.ndarray'>
[6 7 8 9]
[6 1 8 9]
[5 6 1 8 9]


In [33]:
import numpy as np

np_array = np.array([1, 2, 3, 4, 5])
print(np_array.shape)


(5,)


In [39]:
import numpy as np

np_arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

for index, row in enumerate(np_arr):
    print(row)



[1 2 3 4 5]
[ 6  7  8  9 10]
